# There are two databases for each environment, plus one for the MySQL master
# in production.
#
# 1. The Rails database
# 2. The EOL species database. Writing is not allowed to this database
# 3. The master_database connection is used in production mode. It is the
#    database master for writes for the standard Rails database
#
# For developers:
# 1. Make sure to setup your +development+ and +test+ environments
#
# Common settings for each environment assume that all four databases are on
# the same database server for each environment.  If this is not the case,
# you will need to manually edit the entries below the +common+ settings for
# each database in that environment.
#
# The convention for database names is "eol_<DATABASENAME>_<Rails.env>"


# common settings for all production databases
common: &common
  adapter: mysql
  encoding: utf8
  reconnect: true
  # socket: /var/run/mysqld/mysqld.sock

# common settings for any development databases
devel_common: &dev
  host: localhost
  username: root
  password: 

# common settings for all test databases
tst_common: &tst
  host: localhost
  username: root
  password: 

# common settings for all integration databases
int_common: &remote
  host: remote.example.com
  username: user
  password: password



#######################
development:
  <<: *common
  <<: *dev
  database: eol_development

development_data:
  <<: *common
  <<: *dev
  database: eol_data_development

development_logging:
  <<: *common
  <<: *dev
  database: eol_logging_development

############################
test: &test
  <<: *common
  <<: *tst
  database: eol_test

test_data:
  <<: *common
  <<: *tst
  database: eol_data_test

test_logging:
  <<: *common
  <<: *tst
  database: eol_logging_test

# for testing read/write splitting
test_master:
  <<: *common
  <<: *tst
  database: eol_test_master

test_master_data:
  <<: *common
  <<: *tst
  database: eol_data_test_master

test_master_logging:
  <<: *common
  <<: *tst
  database: eol_logging_test_master


############################
integration:
  <<: *common
  <<: *remote
  database: eol_integration

integration_data:
  <<: *common
  <<: *remote
  database: eol_data_integration

integration_logging:
  <<: *common
  <<: *remote
  database: eol_logging_production

############################
staging:
  <<: *common
  <<: *remote
  database: eol_staging

staging_data:
  <<: *common
  <<: *remote
  database: eol_data_staging

staging_logging:
  <<: *common
  <<: *remote
  database: eol_logging_production

############################
 #for production only
 #master database connection for rails database
master_database:
  <<: *common
  <<: *remote
  database: eol_integration

#master database connection for data database
master_data_database:
  <<: *common
  <<: *remote
  database: eol_data_integration

#master database connection for logging database
master_logging_database:
  <<: *common
  <<: *remote
  database: eol_logging_production
